### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by formulake** [choey/Comfy-Topaz#12]
Runs just fine the first time and then throws up this error when the image is changed:

```
Comfy-Topaz: tpaie.exe STDERR: Checking if log directory should be pruned. Currently have 11 log files.
Number of logs exceeds max number to keep ( 10 ). Cleaning excess logs.
Logger initialized
Warning: failed to load Config_git.pl, something strange about this perl...
[ WARN:0@1.070] global matrix_expressions.cpp:1334 cv::MatOp_AddEx::assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739
Error | Exception: "[json.exception.type_error.302] type must be number, but is string"
Error | [CLI] Engine returned error: "Error running model"

!!! Exception during processing !!! [Errno 2] No such file or directory: 'F:\\ComfyUI\\temp\\upscaled\\tpai-1728103156631-1.png'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 267, in upscale_image
    upscaled_image = self.load_image(upscaled_img_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 154, in load_image
    i = Image.open(image_path)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\venv\Lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\temp\\upscaled\\tpai-1728103156631-1.png'
```

**Comment by xueqing0622** [comment]
same problem,

**Comment by neal0829** [comment]
怎么解决？
