### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'  

### ISSUE THREAD

**Issue by xueqing0622** [choey/Comfy-Topaz#15]
Prompt executed in 26.50 seconds
got prompt
Comfy-Topaz: upscaler override: <Comfy-Topaz.topaz.TopazUpscaleSettings object at 0x000001ED4F54D690>
Comfy-Topaz: sharpen override: <Comfy-Topaz.topaz.TopazSharpenSettings object at 0x000001ED51A3BC90>
Comfy-Topaz: tpaie.exe args: ['G:\\Topaz Photo AI\\tpai.exe',
 '--output',
 'F:\\ComfyUI\\ComfyUI\\temp\\upscaled',
 '--compression',
 '2',
 '--format',
 'png',
 '--showSettings',
 '--upscale',
 'scale=2',
 'param1=0.2',
 'param2=0.2',
 'param3=0.2',
 'model=High Fidelity V2',
 '--sharpen',
 'model=Sharpen Strong',
 'compression=0.5',
 'is_lens=false',
 'lensblur=0',
 'mask=false',
 'motionblur=0',
 'noise=0',
 'param1=0',
 'param2=0',
 'F:\\ComfyUI\\ComfyUI\\temp\\tpai-1730379870867-1.png']
Exception in thread Thread-30 (_readerthread):
Traceback (most recent call last):
  File "F:\ComfyUI\python_embeded\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "F:\ComfyUI\python_embeded\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "F:\ComfyUI\python_embeded\Lib\subprocess.py", line 1599, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 731: illegal multibyte sequence
Comfy-Topaz: tpaie.exe return code: 0
Comfy-Topaz: tpaie.exe STDOUT: None
Comfy-Topaz: tpaie.exe STDERR: Checking if log directory should be pruned. Currently have 6 log files.
Log file count is within bounds
Logger initialized
Error | Invalid token structure QList("")
Warning: failed to load Config_git.pl, something strange about this perl...
[ WARN:0@1.760] global matrix_expressions.cpp:1334 cv::MatOp_AddEx::assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739

!!! Exception during processing !!! 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 266, in upscale_image
    (upscaled_img_file, user_settings, autopilot_settings) = self.topaz_upscale(img_file, compression, format, tpai_exe=tpai_exe, upscale=upscale, sharpen=sharpen)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 246, in topaz_upscale
    user_settings, autopilot_settings = self.get_settings(p_tpai.stdout)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 166, in get_settings
    settings_start = stdout.find('Final Settings for')
                     ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by xueqing0622** [comment]
topaz photoAI version is 3.20

**Comment by xueqing0622** [comment]
after download all models, FileNotFoundError: [Errno 2] No such file or directory: 'F:\ComfyUI\ComfyUI\temp\upscaled\tpai-1730421901192-1.png'

> Comfy-Topaz: upscaler override: <Comfy-Topaz.topaz.TopazUpscaleSettings object at 0x00000232CA846590>
Comfy-Topaz: sharpen override: <Comfy-Topaz.topaz.TopazSharpenSettings object at 0x00000232CA8F74D0>
Comfy-Topaz: tpaie.exe args: ['G:\\Topaz Photo AI\\App\\Topaz Photo AI\\tpai.exe',
 '--output',
 'F:\\ComfyUI\\ComfyUI\\temp\\upscaled',
 '--compression',
 '2',
 '--format',
 'png',
 '--showSettings',
 '--upscale',
 'scale=2',
 'param1=0.2',
 'param2=0.2',
 'param3=0.2',
 'model=Standard V2',
 '--sharpen',
 'model=Sharpen Standard',
 'compression=0.5',
 'is_lens=false',
 'lensblur=0',
 'mask=false',
 'motionblur=0',
 'noise=0',
 'param1=0',
 'param2=0',
 'F:\\ComfyUI\\ComfyUI\\temp\\tpai-1730421901192-1.png']
Comfy-Topaz: tpaie.exe return code: 0
Comfy-Topaz: tpaie.exe STDOUT: Change the following settings within the preferences panel in the app
Application settings:
  Overwrite Files: 0
  Recurse Directories: 0
  Input File Count: 1
  Output Folder: F:\ComfyUI\ComfyUI\temp\upscaled
  Output Format: PNG
  Png compression level: 2
Autopilot settings:
  Auto apply filters: true (Forced)
  Face Detection: auto
  Face Strength: 80
  Face Parts: hair,necks
  Sharpen Model: Auto
  Sharpen Levels: medium,high
  Upscaling Model: Auto
  Auto Upscaling Type: auto
  Auto Upscaling Factor: 2
  Upscaling Denoise Strength: 3
  Upscaling Deblur Strength: 3
  Resolution Unit: 1
  Resolution: -1
  Denoise (non-RAW) Model: Auto
  Denoise (non-RAW) Levels: medium,high,severe
  Denoise (RAW) Model: Auto
  Denoise (RAW) Levels: low,medium,high,severe
  Denoise (RAW) Strength: 3
  Denoise vs Sharpen: auto
  Adjust Lighting Strength: 25
  Adjust Lighting RAW Strength: 8
  Balance Color Temperature: 50
  Balance Color Opacity: 100
  Default Subject Type: Subject
Overwriting Sharpen enabled to true
Overwriting Sharpen param2 to 0
Overwriting Sharpen param1 to 0
Overwriting Sharpen noise to 0
Overwriting Sharpen motionblur to 0
Overwriting Sharpen mask to false
Overwriting Sharpen lensblur to 0
Overwriting Sharpen is_lens to false
Overwriting Sharpen compression to 0.5
Overwriting Sharpen model to Sharpen Standard
Overwriting Enhance enabled to true
Overwriting Enhance model to Standard V2
Overwriting Enhance param3 to 0.2
Overwriting Enhance param2 to 0.2
Overwriting Enhance param1 to 0.2
Overwriting Enhance scale to 2
Final Settings for F:\ComfyUI\ComfyUI\temp\tpai-1730421901192-1.png:
{
    "Enhance": {
        "category": "Enhance",
        "enabled": true,
        "model": "Standard V2",
        "params": {
            "height": 3254,
            "locked": false,
            "mode": "scale",
            "param1": "0.2",
            "param2": "0.2",
            "param3": "0.2",
            "resolution": 72,
            "resolutionUnit": 1,
            "scale": "2",
            "width": 3686
        },
        "subjectSettings": {
        }
    },
    "Sharpen": {
        "category": "Sharpen",
        "enabled": true,
        "model": "Sharpen Standard",
        "params": {
            "auto": true,
            "compression": "0.5",
            "deselectedByUpscaling": false,
            "isLens": false,
            "is_lens": "false",
            "lensblur": "0",
            "locked": false,
            "mask": "false",
            "motionblur": "0",
            "noise": "0",
            "param1": "0",
            "param2": "0",
            "slens2_blur": 0.5771915912628174,
            "slens2_noise": 0.06499999761581421,
            "slens_blur": 0.11864107847213745,
            "slens_noise": 0.044943973422050476,
            "smot_blur": 0.2572518587112427,
            "smot_noise": 0.044943973422050476,
            "snat_blur": 0.11864107847213745,
            "snat_noise": 0.044943973422050476,
            "srf_blur": 0.11864107847213745,
            "srf_noise": 0.044943973422050476,
            "std_blur": 0.5771915912628174,
            "std_noise": 0.06499999761581421,
            "stg_blur": 0.2562693655490875,
            "stg_noise": 0.05000000074505806
        },
        "subjectSettings": {
            "feathering": 1,
            "model": "Subject",
            "originalSubjectPath": "",
            "sensitivity": 0.5,
            "strokes": [
            ]
        }
    },
    "applyAutopilotOnceCalculated": false,
    "autoPilot": 1,
    "autoPilotSettings": {
        "Denoise": {
            "auto": true,
            "category": "Denoise",
            "deselectedByUpscaling": false,
            "enabled": false,
            "locked": false,
            "mask": true,
            "model": "Low Light Beta",
            "param1": 0.044943973422050476,
            "param1_normalv2": 0.2489887923002243,
            "param1_strongv2": 0.2425987869501114,
            "param2": 0.2572518587112427,
            "param2_normalv2": 0.12862592935562134,
            "param2_strongv2": 0.12862592935562134,
            "params": {
                "auto": true,
                "deselectedByUpscaling": false,
                "locked": false,
                "mask": true,
                "param1": 0.044943973422050476,
                "param1_normalv2": 0.2489887923002243,
                "param1_strongv2": 0.2425987869501114,
                "param2": 0.2572518587112427,
                "param2_normalv2": 0.12862592935562134,
                "param2_strongv2": 0.12862592935562134,
                "recover_detail": 0
            },
            "recover_detail": 0
        },
        "Enhance": {
            "category": "Enhance",
            "enabled": true,
            "height": 3254,
            "locked": false,
            "mode": "scale",
            "model": "Standard V2",
            "param1": 0.2530277371406555,
            "param2": 0.7032666802406311,
            "param3": 0.48556703329086304,
            "params": {
                "height": 3254,
                "locked": false,
                "mode": "scale",
                "param1": 0.2530277371406555,
                "param2": 0.7032666802406311,
                "param3": 0.48556703329086304,
                "resolution": 72,
                "resolutionUnit": 1,
                "scale": 1.7999999523162842,
                "width": 3686
            },
            "resolution": 72,
            "resolutionUnit": 1,
            "scale": 1.7999999523162842,
            "width": 3686
        },
        "Exposure Adjust": {
            "auto": true,
            "category": "Exposure Adjust",
            "enabled": false,
            "locked": false,
            "mask": true,
            "param1": 0.25,
            "params": {
                "auto": true,
                "locked": false,
                "mask": true,
                "param1": 0.25
            }
        },
        "Face Recovery": {
            "category": "Face Recovery",
            "enabled": false,
            "faceOption": "auto",
            "faceParts": [
                "hair",
                "necks"
            ],
            "highConfidenceFaces": [
            ],
            "locked": false,
            "lowConfidenceFaces": [
                0,
                1,
                2,
                3
            ],
            "param1": 0.800000011920929,
            "params": {
                "faceOption": "auto",
                "faceParts": [
                    "hair",
                    "necks"
                ],
                "highConfidenceFaces": [
                ],
                "locked": false,
                "lowConfidenceFaces": [
                    0,
                    1,
                    2,
                    3
                ],
                "param1": 0.800000011920929,
                "selectedFaces": [
                ]
            },
            "selectedFaces": [
            ]
        },
        "RAW": {
            "params": {
            }
        },
        "Sharpen": {
            "auto": true,
            "category": "Sharpen",
            "compression": 0.5369671583175659,
            "deselectedByUpscaling": false,
            "enabled": false,
            "isLens": false,
            "locked": false,
            "mask": true,
            "model": "Sharpen Standard v2",
            "param1": 0.06499999761581421,
            "param2": 0.5771915912628174,
            "params": {
                "auto": true,
                "compression": 0.5369671583175659,
                "deselectedByUpscaling": false,
                "isLens": false,
                "locked": false,
                "mask": true,
                "param1": 0.06499999761581421,
                "param2": 0.5771915912628174,
                "slens2_blur": 0.5771915912628174,
                "slens2_noise": 0.06499999761581421,
                "slens_blur": 0.11864107847213745,
                "slens_noise": 0.044943973422050476,
                "smot_blur": 0.2572518587112427,
                "smot_noise": 0.044943973422050476,
                "snat_blur": 0.11864107847213745,
                "snat_noise": 0.044943973422050476,
                "srf_blur": 0.11864107847213745,
                "srf_noise": 0.044943973422050476,
                "std_blur": 0.5771915912628174,
                "std_noise": 0.06499999761581421,
                "stg_blur": 0.2562693655490875,
                "stg_noise": 0.05000000074505806
            },
            "slens2_blur": 0.5771915912628174,
            "slens2_noise": 0.06499999761581421,
            "slens_blur": 0.11864107847213745,
            "slens_noise": 0.044943973422050476,
            "smot_blur": 0.2572518587112427,
            "smot_noise": 0.044943973422050476,
            "snat_blur": 0.11864107847213745,
            "snat_noise": 0.044943973422050476,
            "srf_blur": 0.11864107847213745,
            "srf_noise": 0.044943973422050476,
            "std_blur": 0.5771915912628174,
            "std_noise": 0.06499999761581421,
            "stg_blur": 0.2562693655490875,
            "stg_noise": 0.05000000074505806
        },
        "Text Recovery": {
            "auto": true,
            "category": "Text Recovery",
            "enabled": false,
            "locked": false,
            "model": "",
            "param1_noisy": 0.2489887923002243,
            "param1_normal": 0.30363328456878663,
            "param2_noisy": 0.12862592935562134,
            "param2_normal": 0.8386099934577942,
            "param3_noisy": 0,
            "param3_normal": 0.5826804399490356,
            "param4": 0.9,
            "params": {
                "auto": true,
                "locked": false,
                "param1_noisy": 0.2489887923002243,
                "param1_normal": 0.30363328456878663,
                "param2_noisy": 0.12862592935562134,
                "param2_normal": 0.8386099934577942,
                "param3_noisy": 0,
                "param3_normal": 0.5826804399490356,
                "param4": 0.9,
                "strokes": [
                ]
            },
            "strokes": [
            ]
        },
        "White Balance Adjust": {
            "auto": true,
            "category": "White Balance Adjust",
            "enabled": false,
            "locked": false,
            "mask": true,
            "params": {
                "auto": true,
                "locked": false,
                "mask": true,
                "strength": 1,
                "temperature": 0.5
            },
            "strength": 1,
            "temperature": 0.5
        }
    },
    "blur_level": -1,
    "changesCount": 21,
    "initialFiltersApplied": false,
    "justSaved": false,
    "noise_level": -1,
    "presetAppliedNoModifications": false,
    "presetsApplied": [
    ]
}


Comfy-Topaz: tpaie.exe STDERR: Checking if log directory should be pruned. Currently have 3 log files.
Log file count is within bounds
Logger initialized
Error | Invalid token structure QList("")
Warning: failed to load Config_git.pl, something strange about this perl...
[ WARN:0@1.703] global matrix_expressions.cpp:1334 cv::MatOp_AddEx::assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739
Error | Exception: "[json.exception.type_error.302] type must be number, but is string"
Error | [CLI] Engine returned error: "Error running model"

!!! Exception during processing !!! [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI\\temp\\upscaled\\tpai-1730421901192-1.png'
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 267, in upscale_image
    upscaled_image = self.load_image(upscaled_img_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\Comfy-Topaz\topaz.py", line 154, in load_image
    i = Image.open(image_path)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI\\temp\\upscaled\\tpai-1730421901192-1.png'

**Comment by 15138976136** [comment]
Same question, how to solve it

**Comment by 15138976136** [comment]
Same question, how to solve it
